### PR TITLE
update nalgebra version

### PR DESCRIPTION
**Pull request by alexbool**

### CODE REVIEW

**Comment by phaazon** [comment]
Great, thanks! I’ll update that tomorrow! :)

**Comment by phaazon** [comment]
Erm, compilation doesn’t pass. Why the CI didn’t fire up? I’m reverting the merge.

**Comment by phaazon** [comment]
This version has breaking changes and needs code to be updated. I will check why the CI didn’t fire up.

**Comment by alexbool** [comment]
Hmmm, tests passed locally...

**Comment by phaazon** [comment]
`nalgebra` is an optional dependency and disabled by default so that people don’t mistakenly download it. Maybe that’s why.

**Comment by alexbool** [comment]
`cargo test --features "impl-nalgebra"` was the command I used

**Pull request merged**
