### PR TITLE
Update nalgebra 0.20 (take 2)

### PR DESCRIPTION
**Pull request by alexbool**
I think I fixed the problem that was due to addition of non-Copy scalar types in `nalgebra` 0.20

### CODE REVIEW

**Comment by alexbool** [comment]
CI is failing because of code is not formatted. Should I format the whole repo in this PR?

**Comment by phaazon** [comment]
Looking at the errors, it’s should about the examples. :)

**Comment by alexbool** [comment]
Formatted all the code, CI green

**Comment by phaazon** [comment]
Thank you very much! :)

**Comment by phaazon** [comment]
Published as `splines-3.2`.

**Pull request merged**
